/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javatcp_lampu_kita;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.ImageIcon;

/**
 *
 * @author Ulfa
 */
public class Server_lampu extends javax.swing.JFrame {
    
    private static ImageIcon hitam = new ImageIcon("src/javaTCP_lampu_kita/hitam.png");
    private static ImageIcon merah = new ImageIcon("src/javaTCP_lampu_kita/merahOn.png");
    private static ImageIcon kuning = new ImageIcon("src/javaTCP_lampu_kita/kuningOn.png");
    private static ImageIcon hijau = new ImageIcon("src/javaTCP_lampu_kita/hijauOn.png");
    
    static ServerSocket serverSoc;
    static Socket sk;
   
    static DataInputStream dataInput;

    /**
     * Creates new form Server_lampu
     */
    public Server_lampu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_lampu_merah = new javax.swing.JLabel();
        jLabel_lampu_kuning = new javax.swing.JLabel();
        jLabel_lampu_hijau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_lampu_merah.setIcon(new javax.swing.ImageIcon("D:\\Project_netbeans\\JavaTCP_lampu_kita\\src\\javatcp_lampu_kita\\hitam.png")); // NOI18N

        jLabel_lampu_kuning.setIcon(new javax.swing.ImageIcon("D:\\Project_netbeans\\JavaTCP_lampu_kita\\src\\javatcp_lampu_kita\\hitam.png")); // NOI18N

        jLabel_lampu_hijau.setIcon(new javax.swing.ImageIcon("D:\\Project_netbeans\\JavaTCP_lampu_kita\\src\\javatcp_lampu_kita\\hitam.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_lampu_hijau)
                    .addComponent(jLabel_lampu_kuning)
                    .addComponent(jLabel_lampu_merah))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_lampu_merah)
                .addGap(32, 32, 32)
                .addComponent(jLabel_lampu_kuning)
                .addGap(37, 37, 37)
                .addComponent(jLabel_lampu_hijau)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_lampu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_lampu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_lampu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_lampu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_lampu().setVisible(true);
            }
        });
        
        
        String line = "";
                try{
                    serverSoc = new ServerSocket(12345);
                    sk = serverSoc.accept();
//                    buffer = new BufferedReader(new InputStreamReader(sk.getInputStream()));

                    dataInput = new DataInputStream(sk.getInputStream());
                    while (!line.equals("Exit")) {
//                        respon=br.readLine();
                        line=dataInput.readUTF();
                        System.out.println(line);
                        
                        if(line.equals("Merah")){
                            jLabel_lampu_merah.setIcon(merah);
                            jLabel_lampu_kuning.setIcon(hitam);
                            jLabel_lampu_hijau.setIcon(hitam);
                            
                        }else if(line.equals("Kuning")){
                            jLabel_lampu_merah.setIcon(hitam);
                            jLabel_lampu_kuning.setIcon(kuning);
                            jLabel_lampu_hijau.setIcon(hitam);
                           
                        }else if(line.equals("Hijau")){
                            jLabel_lampu_merah.setIcon(hitam);
                            jLabel_lampu_kuning.setIcon(hitam);
                            jLabel_lampu_hijau.setIcon(hijau);
                        }
                        else if(line.equals("Mati")){
                            jLabel_lampu_merah.setIcon(hitam);
                            jLabel_lampu_kuning.setIcon(hitam);
                            jLabel_lampu_hijau.setIcon(hitam);
                            System.exit(0);
                        }
//                       dataOutput.close();
                    }
                    sk.close();
                } catch (Exception e) {
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel jLabel_lampu_hijau;
    private static javax.swing.JLabel jLabel_lampu_kuning;
    private static javax.swing.JLabel jLabel_lampu_merah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
